language: python

notifications:
  email: false

python:
  - "2.7"
  - "3.5"

sudo: false

before_install:
  # make sure we have wheel and setuptools
  - pip install -U pip wheel setuptools
  - pip install --only-binary=numpy numpy

install:
  - python setup.py install

script:
  # test import
  - python -c 'import slots'

# cashe pip
cache:
  directories:
    - $HOME/.cache/pip
